[packages.apt]
    to_remove = []
    [packages.apt.common]
        packages = [
            "gh",
            "starship"
        ]

[packages.homebrew]
    to_remove = []
    [packages.homebrew.common]
    casks = []
    formulae = [
        "gh",
        "starship",
        "commitizen"
    ]
