[packages.apt]
    to_remove = []
    [packages.apt.common]
        packages = [
            "starship"
        ]

[packages.homebrew]
    to_remove = []
    [packages.homebrew.common]
    casks = []
    formulae = [
        "starship"
    ]
